### ISSUE TITLE
reply to email with comments. 

### ISSUE THREAD

**Issue by simonv3** [simonv3/ideas#10]

**Comment by simonv3** [comment]
http://docs.webfaction.com/user-guide/email.html#sending-mail-to-a-script

**Comment by simonv3** [comment]
this will be voided with having weekly emails instead - make sense @RichardLitt ?

**Comment by RichardLitt** [comment]
yeah

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt
