### ISSUE TITLE
blocking specific users? 

### ISSUE THREAD

**Issue by simonv3** [simonv3/ideas#21]
do we really want this? this is just from the main site page?

**Comment by RichardLitt** [comment]
Well, not for us, but for users.

**Comment by simonv3** [comment]
on the front page? maybe they can subscribe to users' ideas, but on the home page it should just be everyone's ideas?

**Comment by RichardLitt** [comment]
What if I hate a person? Also, won't that be a lot of ideas?

**Comment by simonv3** [comment]
Yeah, is that a problem?

**Comment by RichardLitt** [comment]
No, I guess not.
