### ISSUE TITLE
profile pictures

### ISSUE THREAD

**Issue by simonv3** [simonv3/ideas#22]
don't think this is really necessary. it's about the ideas, not the people posting the ideas?

**Comment by RichardLitt** [comment]
Necessary. Gives humanity to it.

**Comment by simonv3** [comment]
fuck humans.

**Comment by RichardLitt** [comment]
I like to ___

**Comment by simonv3** [comment]
i'll do this next weekend, but i think before that i'm going to focus on making the information structure of some of the pages of the website make more sense. there's too much going on on the home page.

**Comment by RichardLitt** [comment]
cheers. I probably can't do it.

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt
