### ISSUE TITLE
create dev site

### ISSUE THREAD

**Issue by simonv3** [simonv3/ideas#31]

**Comment by simonv3** [comment]
there's a dev site up at dev.ideaotter.com check it out, maybe post ideas there?

**Comment by RichardLitt** [comment]
aight

## 

Richard Littauer
MSc Computational Linguistics
University of Saarland
http://www.rlittauer.com | @richlitt

On Wed, Apr 4, 2012 at 2:18 AM, Simon <
reply@reply.github.com
