### ISSUE TITLE
people who register with an email address as a username don't seem to get verified

### ISSUE THREAD

**Issue by simonv3** [simonv3/ideas#37]
probably because of some error in sending to the create_user function

**Comment by RichardLitt** [comment]
Might be as simple as a unicode @ error.

**Comment by simonv3** [comment]
no, it's something to do with django internally i think. because i don't
specify it as a username on logging in (not sure i do, haven't checked) it
recognizes it as an email, and as a result stores it as an email. really i
should be doing an internal check to see if it's an email and send a
verification in that case.
