### ISSUE TITLE
IdeaOtter on the main page

### ISSUE THREAD

**Issue by RichardLitt** [simonv3/ideas#38]
You can't see the otter and the ideas together!

**Comment by simonv3** [comment]
have you tried searching for an idea that doesn't exist? (i haven't quite
figured out where to put the otter on the main page)

**Comment by RichardLitt** [comment]
I am in love.

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by RichardLitt** [comment]
The otter should go in the top bar.

**Comment by simonv3** [comment]
can you give me a resized small version that looks okay? if not i can probably ask olivia to draw one, but i would prefer to try that.

**Comment by RichardLitt** [comment]
is it too big? I would just edit it in Illustrator/Photoshop. That ok?

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
fine by me!

**Comment by RichardLitt** [comment]
will work on it. assign to me?

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt
