### ISSUE TITLE
Slates

### ISSUE THREAD

**Issue by RichardLitt** [simonv3/ideas#40]
Get slates going - blank slates, 5- free, 5+ cost, for companies and teams to work together. Can push to the main site if they like, afterwards, either in bulk or individually. Should be a default to push?

**Comment by simonv3** [comment]
how do you mean push to main site? I figured it would be on the main site anyway?

**Comment by RichardLitt** [comment]
I thought the point was to have a clean slate, and generate ideas for that?
So, you'd only see ideas from that slate. Then, at the end, you can either
clean the slate and delete the entries, or brush all of the ideas onto the
main site...

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
oh right, when you said push i thought you meant have it not enabled on the
main site yet at all. thinking git

**Comment by RichardLitt** [comment]
my bad.

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
done as of today phew

**Comment by RichardLitt** [comment]
Woot!

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt
