### ISSUE TITLE
Hyperlink Function

### ISSUE THREAD

**Issue by RichardLitt** [simonv3/ideas#41]

**Comment by simonv3** [comment]
is this within ideas?

**Comment by RichardLitt** [comment]
Yes.

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
should they appear withink the ideas on the home page, or not? I think
having them appear on the home page might be too cluttered?

**Comment by RichardLitt** [comment]
I think it would be good to shorten them to an icon of a chain, or a [link]
button. At least say that there is a link, somehow.

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt
