### ISSUE TITLE
Donation page

### ISSUE THREAD

**Issue by RichardLitt** [simonv3/ideas#43]

**Comment by simonv3** [comment]
can you write this? also rethink the about page, at the moment i think it's too confusing. i might re-arrange the text, be more like tigatag about http://www.tigatag.com/about/

**Comment by RichardLitt** [comment]
Yeah. I think I assigned it to me? I can rewrite the about page, too. I
agree.

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by RichardLitt** [comment]
@simonv3 Update on this?

**Comment by simonv3** [comment]
This whole repo can probably be closed since https://apps.sandstorm.io/app/du1nkmp0edheyjq07rm8s1tzr4qs4ut7k24vc2ps0vzm30zp77y0 is a thing now.

**Comment by RichardLitt** [comment]
Assuming that's the end all for it, yeah.

**Comment by simonv3** [comment]
It is for me! It's all open source, so you're welcome to take it other places. 

#closure.
