### ISSUE TITLE
More local information about the developers and site on the about page

### ISSUE THREAD

**Issue by RichardLitt** [simonv3/ideas#45]

**Comment by simonv3** [comment]
more local? you mean you want your name on it as a developer?

**Comment by RichardLitt** [comment]
...and yours?

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
i'm not too fussed, my name is on all the commits ;)

**Comment by RichardLitt** [comment]
Do we even have a link to github up?

**Comment by RichardLitt** [comment]
Should we add one, or are we basically going private on Git soon?

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
did you not see my e-mail?

On Tue, Sep 25, 2012 at 12:13 AM, Richard Littauer <notifications@github.com

> wrote:
> 
> Should we add one, or are we basically going private on Git soon?
> 
> ## 
> 
> Erasmus Mundus MSc Computational Linguistics | University of Malta
> http://www.rlittauer.com | @richlitt
> 
> On Mon, Sep 24, 2012 at 6:48 PM, Richard Littauer <

**Comment by RichardLitt** [comment]
Yeah. I guess I ignored it?

## 

Erasmus Mundus MSc Computational Linguistics | University of Malta
http://www.rlittauer.com | @richlitt

**Comment by simonv3** [comment]
zing

On Tue, Sep 25, 2012 at 10:59 AM, Richard Littauer <notifications@github.com

> wrote:
> 
> Yeah. I guess I ignored it?
> 
> ## 
> 
> Erasmus Mundus MSc Computational Linguistics | University of Malta
> http://www.rlittauer.com | @richlitt
>
